--ejecutar script en la base de datos firebird 3.0

CREATE TABLE clientes
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    ciudad VARCHAR(50)
);

CREATE TABLE productos
(
    id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50)    NOT NULL,
    precio NUMERIC(10, 2) NOT NULL
);

CREATE TABLE facturas
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    fecha      DATE DEFAULT CURRENT_DATE,
    total      NUMERIC(10, 2),
    FOREIGN KEY (id_cliente) REFERENCES clientes (id)
);

CREATE TABLE detalle_factura
(
    id_factura  INT NOT NULL,
    id_producto INT NOT NULL,
    cantidad    INT NOT NULL,
    subtotal    NUMERIC(10, 2),
    PRIMARY KEY (id_factura, id_producto),
    FOREIGN KEY (id_factura) REFERENCES facturas (id),
    FOREIGN KEY (id_producto) REFERENCES productos (id)
);

-- tabla clientes
INSERT INTO clientes (nombre, ciudad) VALUES ('Juan Pérez', 'Buenos Aires');
INSERT INTO clientes (nombre, ciudad) VALUES ('María López', 'Córdoba');

-- tabla productos
INSERT INTO productos (nombre, precio) VALUES ('Mouse', 1500.00);
INSERT INTO productos (nombre, precio) VALUES ('Teclado', 4000.00);
INSERT INTO productos (nombre, precio) VALUES ('Monitor', 60000.00);

-- tabla facturas
INSERT INTO facturas (id_cliente, fecha, total) VALUES (1, '2024-05-10', 63000.00);
INSERT INTO facturas (id_cliente, fecha, total) VALUES (2, '2024-05-12', 4000.00);

-- tabla detalle_factura
INSERT INTO detalle_factura (id_factura, id_producto, cantidad, subtotal) VALUES (1, 3, 1, 60000.00);
INSERT INTO detalle_factura (id_factura, id_producto, cantidad, subtotal) VALUES (1, 1, 2, 3000.00);
INSERT INTO detalle_factura (id_factura, id_producto, cantidad, subtotal) VALUES (2, 2, 1, 4000.00);
